_homepage:
    pattern: /
    defaults: { _controller: MyFormRPBundle:Default:new }

_list:
    pattern: /lista
    defaults: { _controller: MyFormRPBundle:Default:list }

_edit:
    pattern: /edit/{id}
    defaults: { _controller: MyFormRPBundle:Default:edit }